In [13]:
#this is a test commit

import pandas as pd
import numpy as np

print ("test commit")

3+3

test commit


6

In [14]:
#test commit

x = 5

z = 7

x+z

12

In [15]:
print ('test commit 2')

test commit 2


In [16]:
print('commit 6')

commit 6


In [17]:
#testimport6

In [18]:
print('Import7')

Import7


In [19]:
print ('new commit read me')

new commit read me


In [20]:
x = (1,2,4,
     6,3,7,
     3,6,9)
print (x)

(1, 2, 4, 6, 3, 7, 3, 6, 9)


In [21]:
print (x)

(1, 2, 4, 6, 3, 7, 3, 6, 9)


In [42]:
matrix_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [43]:
print(matrix_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
 print('Homer Simpson')


Homer Simpson


In [53]:
print("test")

test
