In [13]:
#this is a test commit

import pandas as pd
import numpy as np

print ("test commit")

3+3

test commit


6

In [14]:
#test commit

x = 5

z = 7

x+z

12

In [15]:
print ('test commit 2')

test commit 2


In [16]:
print('commit 6')

commit 6


In [17]:
#testimport6

In [18]:
print('Import7')

Import7


In [19]:
print ('new commit read me')

new commit read me


In [20]:
x = (1,2,4,
     6,3,7,
     3,6,9)
print (x)

(1, 2, 4, 6, 3, 7, 3, 6, 9)


In [21]:
print (x)

(1, 2, 4, 6, 3, 7, 3, 6, 9)


In [42]:
matrix_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [43]:
print(matrix_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
 print('Homer Simpson')


Homer Simpson


In [53]:
print("test")

test


In [55]:
dataFrame = pd.read_csv(r"C:\Users\howar\OneDrive\Documents\BU Mod1\Data\Data.csv")

print(dataFrame)

     Wins  Single  Double  Triple  Homerun    SO  Walks  Pitcherhr  Pitcherbb  \
0      84     875     274      44      166  1247    540        197        525   
1     104     920     293      23      307  1289    538        187        534   
2     101     879     309      28      183  1370    512        177        473   
3      78     897     339      19      182  1372    486        208        497   
4      83     904     269      30      196  1391    570        179        513   
..    ...     ...     ...     ...      ...   ...    ...        ...        ...   
235   100     922     288      39      137  1267    506        123        477   
236    80     906     278      32      167  1310    436        175        477   
237    88     936     279      32      172  1233    503        171        508   
238    93     923     308      17      232  1151    570        173        397   
239    83     908     265      13      177  1344    539        145        364   

     Pitcherso  Error  Sacr